describe("DAP Infrastructure", function()
  it("should be able to require 'dap'", function()
    assert.is_true(pcall(require, "dap"))
  end)
  it("should be able to require 'dapui'", function()
    assert.is_true(pcall(require, "dapui"))
  end)
  it("should have DAP keybindings mapped", function()
    local map = vim.fn.maparg("<F5>", "n", false, true)
    assert.is_not_nil(map)
    assert.is_true(map.desc:find("Debug") ~= nil)
  end)
end)
